name: 'Download  a Build Artifact'
description: 'Download and untar a build artifact that was previously uploaded in the workflow by the upload-artifact action'

inputs:
  name:
    description: 'Artifact name'
    default: 'artifact'
    required: false
  path:
    description: 'Destination path'
    default: '.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: '📥 download artifact'
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.name }}.tar

    - name: '📦 tar inputs'
      shell: 'bash'
      working-directory: ${{ inputs.path }}
      run: |
        tar -xvf artifact.tar
      continue-on-error: true

    - name: '🧹 cleanup'
      shell: 'bash'
      run: rm -f ${{ inputs.name }}.tar
